name: CI

on:
  push:
    branches:
      - master
      - '*.x'
      - feature/* # todo: comment
    paths-ignore:
      - '**.md'

  pull_request:
    branches:
      - master
      - '*.x'
    paths-ignore:
      - '**.md'

jobs:
  package:
    name: Package
    uses: sketch7/.github/.github/workflows/node-lib.yml@feature/node-lib
    with:
      node-version: '18'
      publishable: ${{ contains(fromJSON('["develop", "master", "workflow", "feature/workflow"]'), github.ref_name) || endsWith(github.ref_name, '.x')  }}
    secrets:
      npm-auth-token: ${{ secrets.NPM_KEY }}
